services:
  database:
    image: docker.io/library/postgres:16-alpine
    container_name: rankify-database
    environment:
      POSTGRES_DB: rankify
      POSTGRES_USER: rankify
      POSTGRES_PASSWORD: rankify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rankify -d rankify"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - rankify-network

  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: rankify-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - rankify-network

volumes:
  postgres_data:
    driver: local

networks:
  rankify-network:
    driver: bridge