spring:
  application:
    name: rankify-api
  datasource:
    url: jdbc:postgresql://database:5432/rankify
    username: rankify
    password: rankify
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      enabled: true